services:
  - type: web
    name: portfolio_site_backend
    env: java
    buildCommand: ./mvnw clean install
    startCommand: ./setup.sh && java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        value: ${DB_URL}
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASSWORD
        value: ${DB_PSWD}
      - key: DB_DB_DRIVER
        value: ${DB_DRIVER}
      - key: DB_PLATFORM
        value: ${DB_PLATFORM}
      - key: DB_SHOW
        value: ${DB_SHOW}
      - key: DB_DDL
        value: ${DB_DDL}
      - key: DB_FLYWAY
        value: ${DB_FLYWAY}
