spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PSWD}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.database-platform=${DB_PLATFORM}
spring.jpa.show-sql=${DB_SHOW}
spring.jpa.hibernate.ddl-auto=${DB_DDL}

spring.flyway.enabled=${DB_FLYWAY}
